import type { ExerciseDefinition, MuscleGroup, ExerciseCategory, EquipmentType } from '@/types/fitness'

export const exerciseLibrary: ExerciseDefinition[] = [
  // ─── Chest ───
  {
    id: 'bench_press',
    name: 'Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell'],
    difficulty: 'beginner',
    instructions: [
      'Lie flat on a bench, feet planted firmly on the floor.',
      'Grip the barbell slightly wider than shoulder-width.',
      'Lower the bar to your mid-chest in a controlled motion.',
      'Press the bar back up until arms are fully extended.',
    ],
    tips: ['Keep your core tight throughout.', 'Do not bounce the bar off your chest.'],
  },
  {
    id: 'incline_bench_press',
    name: 'Incline Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Set the bench to a 30-45 degree angle.',
      'Lie back and grip the barbell slightly wider than shoulders.',
      'Lower the bar to your upper chest.',
      'Press up and slightly back toward the rack.',
    ],
    tips: ['Targets the upper chest (clavicular head).', 'Keep elbows tucked slightly.'],
  },
  {
    id: 'dumbbell_flyes',
    name: 'Dumbbell Flyes',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['dumbbell'],
    difficulty: 'intermediate',
    instructions: [
      'Lie on a flat bench holding dumbbells above your chest with palms facing each other.',
      'Slightly bend your elbows and lower your arms out to the sides in a wide arc.',
      'Lower until you feel a stretch in your chest.',
      'Bring the dumbbells back together in a hugging motion.',
    ],
    tips: ['Keep a slight bend in elbows — do not lock them out.', 'Focus on squeezing the chest at the top.'],
  },
  {
    id: 'cable_crossover',
    name: 'Cable Crossover',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    equipment: ['cable'],
    difficulty: 'intermediate',
    instructions: [
      'Set pulleys to highest position.',
      'Grab handles, step forward into a staggered stance.',
      'Bring hands together in front of your body in a wide arc.',
      'Slowly return to starting position.',
    ],
    tips: ['Keep core engaged.', 'Focus on stretching the chest at the top.'],
  },
  {
    id: 'push_ups',
    name: 'Push-ups',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    instructions: [
      'Start in a plank position with hands under shoulders.',
      'Lower your body until chest nearly touches the floor.',
      'Push back up to starting position.',
    ],
    tips: ['Keep body in a straight line.', 'Do not let hips sag or pike.'],
  },
  {
    id: 'diamond_pushups',
    name: 'Diamond Push-ups',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    instructions: [
      'Form a diamond shape with thumbs and index fingers under your chest.',
      'Lower your body until chest touches the diamond.',
      'Push back up.',
    ],
    tips: ['Keep elbows tucked close to body.', 'Great tricep builder.'],
  },
  {
    id: 'dumbbell_press',
    name: 'Dumbbell Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Lie on a bench holding dumbbells at shoulder width.',
      'Press dumbbells up until arms are extended.',
      'Lower with control to starting position.',
    ],
    tips: ['Allows greater range of motion than barbell.', 'Keep wrists straight.'],
  },

  // ─── Back ───
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['hamstrings', 'glutes', 'traps', 'forearms'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Stand with feet hip-width apart, bar over mid-foot.',
      'Hinge at hips, grip the bar just outside legs.',
      'Flatten back, brace core, and drive through heels to stand.',
      'Lock out at the top with hips and knees extended.',
      'Lower with control by hinging at the hips first.',
    ],
    tips: ['Keep bar close to body throughout.', 'Do not round your lower back.'],
  },
  {
    id: 'pull_ups',
    name: 'Pull-ups',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    instructions: [
      'Hang from a pull-up bar with palms facing away, slightly wider than shoulders.',
      'Pull yourself up until chin is above the bar.',
      'Lower with control to full arm extension.',
    ],
    tips: ['Initiate the pull by depressing your shoulder blades.', 'Avoid swinging or kipping.'],
  },
  {
    id: 'chin_ups',
    name: 'Chin-ups',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    instructions: [
      'Hang with palms facing you, shoulder-width grip.',
      'Pull up until chin clears the bar.',
      'Lower under control.',
    ],
    tips: ['More bicep emphasis than pull-ups.', 'Keep core engaged.'],
  },
  {
    id: 'barbell_row',
    name: 'Barbell Bent-Over Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Bend at hips until torso is nearly parallel to the floor.',
      'Grip barbell with palms down, slightly wider than shoulders.',
      'Pull bar to lower chest/upper abdomen.',
      'Lower with control.',
    ],
    tips: ['Keep back flat throughout the movement.', 'Pull elbows back, not just up.'],
  },
  {
    id: 'dumbbell_row',
    name: 'Single-Arm Dumbbell Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Place one knee and hand on a bench, other foot on the floor.',
      'Hold dumbbell in free hand with arm extended.',
      'Pull dumbbell to hip, squeezing shoulder blade back.',
      'Lower with control.',
    ],
    tips: ['Keep back flat and parallel to ground.', 'Pull towards hip, not shoulder.'],
  },
  {
    id: 'lat_pulldown',
    name: 'Wide-Grip Lat Pulldown',
    category: 'strength',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Sit at lat pulldown station and secure thighs.',
      'Grip bar wide with palms facing away.',
      'Pull bar down to upper chest, squeezing lats.',
      'Slowly return bar to starting position.',
    ],
    tips: ['Lean back slightly.', 'Do not use momentum to pull the bar.'],
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: [
      'Sit at cable row station with feet braced.',
      'Grab handle, arms extended, back straight.',
      'Pull handle to your midsection, squeezing shoulder blades together.',
      'Return with control.',
    ],
    tips: ['Do not round your lower back at the stretch.', 'Keep elbows close to body.'],
  },
  {
    id: 't_bar_row',
    name: 'T-Bar Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Straddle the T-bar, bend at hips with flat back.',
      'Grip handles and pull weight to your chest.',
      'Lower with control.',
    ],
    tips: ['Great for mid-back thickness.', 'Use a landmine attachment or corner.'],
  },

  // ─── Shoulders ───
  {
    id: 'overhead_press',
    name: 'Standing Overhead Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'traps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Stand with feet shoulder-width, bar at upper chest level.',
      'Brace core and press bar straight overhead.',
      'Lock out arms at the top.',
      'Lower under control to starting position.',
    ],
    tips: ['Do not arch lower back excessively.', 'Head goes forward slightly at lockout.'],
  },
  {
    id: 'dumbbell_shoulder_press',
    name: 'Seated Dumbbell Shoulder Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Sit on a bench with back support.',
      'Hold dumbbells at shoulder height, palms forward.',
      'Press dumbbells overhead until arms are fully extended.',
      'Lower with control.',
    ],
    tips: ['Keep core tight.', 'Do not let dumbbells touch at the top.'],
  },
  {
    id: 'lateral_raises',
    name: 'Dumbbell Lateral Raises',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Stand holding dumbbells at your sides.',
      'Raise arms out to the sides until parallel with the floor.',
      'Lower slowly.',
    ],
    tips: ['Slight bend in elbows.', 'Do not swing the weights.'],
  },
  {
    id: 'front_raises',
    name: 'Dumbbell Front Raises',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['chest'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Stand holding dumbbells in front of thighs.',
      'Raise one or both arms forward to shoulder height.',
      'Lower with control.',
    ],
    tips: ['Keep core engaged to avoid swinging.', 'Use lighter weight than lateral raises.'],
  },
  {
    id: 'reverse_flyes',
    name: 'Reverse Dumbbell Flyes',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Sit on bench or bend at hips with dumbbells hanging down.',
      'Raise arms out to the sides, squeezing rear delts.',
      'Lower with control.',
    ],
    tips: ['Bend elbows slightly.', 'Keep back flat.'],
  },
  {
    id: 'face_pulls',
    name: 'Cable Face Pulls',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: [
      'Set cable at face height with rope attachment.',
      'Pull rope to your face, separating the ends.',
      'Hold briefly and return.',
    ],
    tips: ['Excellent for rear delt and rotator cuff health.', 'Use lighter weight, focus on form.'],
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    difficulty: 'intermediate',
    instructions: [
      'Start with palms facing you, dumbbells at shoulder height.',
      'Press up and rotate palms outward as you extend arms.',
      'Reverse the motion on the way down.',
    ],
    tips: ['Named after Arnold Schwarzenegger.', 'Hits all three deltoid heads.'],
  },
  {
    id: 'upright_row',
    name: 'Barbell Upright Row',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps', 'biceps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Hold barbell with overhand grip, hands slightly narrower than shoulders.',
      'Lift bar straight up toward chin, elbows high.',
      'Lower with control.',
    ],
    tips: ['Can aggravate shoulders for some - use caution.', 'Use a rope on cable machine for a safer option.'],
  },
  {
    id: 'shrugs',
    name: 'Barbell Shrugs',
    category: 'strength',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['shoulders'],
    equipment: ['barbell'],
    difficulty: 'beginner',
    instructions: [
      'Hold barbell at hip level with overhand grip.',
      'Shrug shoulders up toward ears.',
      'Hold and squeeze at top, lower slowly.',
    ],
    tips: ['Do not roll shoulders.', 'Straight up and down motion.'],
  },

  // ─── Biceps ───
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    difficulty: 'beginner',
    instructions: [
      'Stand holding barbell with palms up, hands shoulder-width.',
      'Curl bar toward your shoulders.',
      'Lower slowly to full extension.',
    ],
    tips: ['Keep elbows tucked at your sides.', 'Do not swing torso for momentum.'],
  },
  {
    id: 'dumbbell_curl',
    name: 'Standing Dumbbell Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Stand holding dumbbells at your sides, palms forward.',
      'Curl weights toward shoulders.',
      'Lower with control.',
    ],
    tips: ['Alternate arms or curl both simultaneously.', 'Keep wrists straight.'],
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Hold dumbbells with palms facing each other (neutral grip).',
      'Curl weights toward shoulders without rotating wrists.',
      'Lower with control.',
    ],
    tips: ['Targets the brachialis and brachioradialis.', 'Great for forearm and bicep thickness.'],
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Lie back on an incline bench.',
      'Hold dumbbells at arms length, palms up.',
      'Curl weights up, keeping upper arms stationary.',
      'Lower slowly, feeling the stretch.',
    ],
    tips: ['Targets the long head of the bicep.', 'Use lighter weight than standing curls.'],
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    difficulty: 'beginner',
    instructions: [
      'Sit at preacher bench, upper arms resting on pad.',
      'Curl bar up, squeezing biceps.',
      'Lower until arms are fully extended.',
    ],
    tips: ['Eliminates body momentum.', 'Great for peak contraction.'],
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Sit on bench, rest elbow on inside of thigh.',
      'Curl dumbbell toward shoulder.',
      'Squeeze at top, lower slowly.',
    ],
    tips: ['Isolate the bicep.', 'Focus on mind-muscle connection.'],
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    category: 'strength',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: [
      'Stand facing cable machine with bar attachment.',
      'Curl bar toward chest.',
      'Lower with control, resisting the pull.',
    ],
    tips: ['Constant tension throughout the range of motion.', 'Good alternative to free weights.'],
  },

  // ─── Triceps ───
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: [
      'Stand at cable station, grip bar with palms down.',
      'Keep elbows pinned at your sides.',
      'Push bar down until arms are fully extended.',
      'Return with control.',
    ],
    tips: ['Do not let elbows flare out.', 'Squeeze triceps at full extension.'],
  },
  {
    id: 'skull_crushers',
    name: 'Skull Crushers (Lying Tricep Extension)',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Lie on bench, hold barbell with arms extended over chest.',
      'Lower bar to forehead by bending elbows.',
      'Extend arms back to starting position.',
    ],
    tips: ['Keep upper arms stationary.', 'Do not let elbows flare.'],
  },
  {
    id: 'close_grip_bench',
    name: 'Close-Grip Bench Press',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Lie on bench with hands placed shoulder-width apart or narrower.',
      'Lower bar to lower chest.',
      'Press back up.',
    ],
    tips: ['Hands should be placed inside shoulder width.', 'Targets triceps more than chest.'],
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Dumbbell Tricep Extension',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Hold dumbbell with both hands overhead, arms extended.',
      'Lower weight behind your head by bending elbows.',
      'Extend arms back up.',
    ],
    tips: ['Keep elbows pointing forward.', 'Use lighter weight to maintain control.'],
  },
  {
    id: 'dips',
    name: 'Parallel Bar Dips',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    instructions: [
      'Mount parallel bars, arms extended.',
      'Lower yourself until upper arms are parallel to floor.',
      'Push back up.',
    ],
    tips: ['Lean forward for more chest emphasis.', 'Upright position targets triceps.'],
  },
  {
    id: 'dumbbell_kickback',
    name: 'Dumbbell Tricep Kickback',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Bend at hips, hold dumbbells with upper arms parallel to torso.',
      'Extend arms straight back.',
      'Return to starting position.',
    ],
    tips: ['Keep upper arms still.', 'Squeeze triceps at peak contraction.'],
  },
  {
    id: 'rope_pushdown',
    name: 'Rope Tricep Pushdown',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: [
      'Attach rope to cable machine.',
      'Push rope down, separating the ends.',
      'Return with control.',
    ],
    tips: ['Separate rope ends at bottom for maximum contraction.', 'Keep elbows at your sides.'],
  },

  // ─── Legs ───
  {
    id: 'squat',
    name: 'Barbell Back Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Place bar on upper back/shoulders.',
      'Stand feet shoulder-width apart, toes slightly outward.',
      'Brace core and squat down until thighs are parallel or below.',
      'Drive through heels to stand back up.',
    ],
    tips: ['Keep chest up and back straight.', 'Do not let knees cave inward.'],
  },
  {
    id: 'front_squat',
    name: 'Barbell Front Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    instructions: [
      'Rest bar across front delts, elbows high.',
      'Squat down, keeping torso as upright as possible.',
      'Drive up through heels.',
    ],
    tips: ['More quad-dominant than back squat.', 'Requires good ankle and wrist mobility.'],
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['dumbbell', 'kettlebell'],
    difficulty: 'beginner',
    instructions: [
      'Hold weight at chest level with both hands.',
      'Squat down, keeping chest up.',
      'Drive up through heels.',
    ],
    tips: ['Excellent squat variation for beginners.', 'Helps teach proper squat mechanics.'],
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Sit in leg press machine, feet on platform shoulder-width.',
      'Lower platform until knees are at 90 degrees.',
      'Press platform back up without locking knees.',
    ],
    tips: ['Do not lock out knees at the top.', 'Lower depth depends on individual mobility.'],
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Sit at leg extension machine, pad on ankles.',
      'Extend legs until fully straight.',
      'Lower with control.',
    ],
    tips: ['Isolate the quads.', 'Go light if you have knee issues.'],
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'back', 'forearms'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Hold barbell with palms down, standing tall.',
      'Hinge at hips, pushing butt back while keeping bar close to legs.',
      'Lower until you feel a stretch in hamstrings.',
      'Drive hips forward to return to standing.',
    ],
    tips: ['Keep knees slightly bent.', 'Back remains flat throughout.'],
  },
  {
    id: 'leg_curl',
    name: 'Lying Leg Curl',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Lie face down on leg curl machine.',
      'Curl heels toward glutes.',
      'Lower with control.',
    ],
    tips: ['Keep hips pressed into the pad.', 'Do not lift hips off the bench.'],
  },
  {
    id: 'walking_lunges',
    name: 'Walking Lunges',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    equipment: ['bodyweight', 'dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Take a step forward into a lunge position.',
      'Lower your back knee near the floor.',
      'Drive through front foot to step forward into next lunge.',
    ],
    tips: ['Keep torso upright.', 'Do not let front knee cave inward.'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight', 'dumbbell'],
    difficulty: 'intermediate',
    instructions: [
      'Stand a few feet in front of a bench, rear foot elevated on bench.',
      'Lower into a lunge until front thigh is parallel.',
      'Drive through front foot to stand.',
    ],
    tips: ['Keep front knee tracking over toes.', 'Great unilateral leg builder.'],
  },
  {
    id: 'hip_thrust',
    name: 'Barbell Hip Thrust',
    category: 'strength',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Sit with upper back against a bench, barbell across hips.',
      'Drive hips up, squeezing glutes at top.',
      'Lower with control.',
    ],
    tips: ['Best glute isolation exercise.', 'Keep chin tucked, look forward.'],
  },
  {
    id: 'calf_raises',
    name: 'Standing Calf Raises',
    category: 'strength',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine', 'bodyweight'],
    difficulty: 'beginner',
    instructions: [
      'Stand on balls of feet on a raised platform.',
      'Lower heels below platform level.',
      'Raise up onto toes as high as possible.',
      'Hold and squeeze at top.',
    ],
    tips: ['Full range of motion is key.', 'Do them slowly for better results.'],
  },
  {
    id: 'seated_calf_raises',
    name: 'Seated Calf Raises',
    category: 'strength',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Sit at calf raise machine, weight on thighs.',
      'Raise heels by contracting calves.',
      'Lower slowly.',
    ],
    tips: ['Targets the soleus (inner calf).', 'Slightly different angle than standing.'],
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Position yourself on hack squat machine.',
      'Lower platform by bending knees.',
      'Drive back up without locking knees.',
    ],
    tips: ['Machine provides stability.', 'Great for high volume quad work.'],
  },
  {
    id: 'box_squat',
    name: 'Box Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    instructions: [
      'Set up a box/bench at parallel height behind you.',
      'Squat down until you sit on the box.',
      'Pause briefly, then drive up.',
    ],
    tips: ['Helps teach squat depth.', 'Common in powerlifting training.'],
  },

  // ─── Abs/Core ───
  {
    id: 'plank',
    name: 'Plank',
    category: 'strength',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'back', 'glutes'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    instructions: [
      'Start in push-up position but on elbows.',
      'Keep body in a straight line from head to heels.',
      'Hold position, engaging core.',
    ],
    tips: ['Do not let hips sag or pike up.', 'Breathe normally throughout.'],
  },
  {
    id: 'hanging_leg_raises',
    name: 'Hanging Leg Raises',
    category: 'strength',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['forearms',

],
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    instructions: [
      'Hang from pull-up bar with arms extended.',
      'Raise legs until parallel to floor or higher.',
      'Lower with control without swinging.',
    ],
    tips: ['Advanced ab exercise.', 'Keep legs as straight as possible.'],
  },
  {
    id: 'crunches',
    name: 'Crunches',
    category: 'strength',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    instructions: [
      'Lie on back, knees bent, feet flat.',
      'Hands behind head or across chest.',
      'Curl upper body off floor, lifting shoulder blades.',
      'Lower slowly.',
    ],
    tips: ['Do not pull on your neck.', 'Focus on crunching with abs, not momentum.'],
  },
  {
    id: 'russian_twists',
    name: 'Russian Twists',
    category: 'strength',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight', 'medicine_ball'],
    difficulty: 'beginner',
    instructions: [
      'Sit with knees bent, lean back slightly.',
      'Rotate torso from side to side, touching floor beside hips.',
    ],
    tips: ['Keep feet elevated for added difficulty.', 'Great for obliques and rotational core strength.'],
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    category: 'strength',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'lats'],
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    instructions: [
      'Kneel and hold ab wheel with hands under shoulders.',
      'Roll forward, extending body.',
      'Roll back to starting position using core.',
    ],
    tips: ['Do not let lower back arch excessively.', 'Start with small range of motion.'],
  },
  {
    id: 'bicycle_crunches',
    name: 'Bicycle Crunches',
    category: 'strength',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    instructions: [
      'Lie on back, hands behind head.',
      'Bring opposite elbow to opposite knee while extending other leg.',
      'Alternate sides in a pedaling motion.',
    ],
    tips: ['Twist from the torso, not just arms.', 'Keep shoulder blades off floor.'],
  },

  // ─── Cardio ───
  {
    id: 'running',
    name: 'Running',
    category: 'cardio',
    primaryMuscles: ['quads', 'hamstrings'],
    secondaryMuscles: ['calves', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Maintain upright posture with slight forward lean.',
      'Land mid-foot, not on heels.',
      'Keep cadence around 170-180 steps per minute.',
      'Breathe rhythmically.',
    ],
    tips: ['Increase mileage gradually (10% rule).', 'Invest in good running shoes.'],
  },
  {
    id: 'cycling',
    name: 'Cycling',
    category: 'cardio',
    primaryMuscles: ['quads', 'hamstrings'],
    secondaryMuscles: ['calves', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Set saddle height so leg is almost straight at bottom of pedal stroke.',
      'Pedal in smooth circles.',
      'Maintain cadence of 80-100 RPM.',
    ],
    tips: ['Low impact cardio option.', 'Great for active recovery.'],
  },
  {
    id: 'rowing',
    name: 'Rowing Machine',
    category: 'cardio',
    primaryMuscles: ['back', 'quads'],
    secondaryMuscles: ['biceps', 'shoulders', 'core'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Drive through legs first, then lean back, then pull handle.',
      'Reverse the order on the return.',
      'Maintain a smooth, continuous rhythm.',
    ],
    tips: ['Legs do 60% of the work.', 'Full-body cardio exercise.'],
  },
  {
    id: 'jump_rope',
    name: 'Jump Rope',
    category: 'cardio',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['shoulders', 'forearms'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Hold rope with hands at hip height.',
      'Rotate wrists, not arms, to swing the rope.',
      'Jump just high enough to clear the rope.',
    ],
    tips: ['Stay light on your feet.', 'Excellent for coordination and cardio.'],
  },
  {
    id: 'elliptical',
    name: 'Elliptical Trainer',
    category: 'cardio',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Place feet on pedals, grip handles.',
      'Move in a fluid elliptical motion.',
      'Adjust resistance and incline for intensity.',
    ],
    tips: ['Very low impact.', 'Reverse direction to target different muscles.'],
  },
  {
    id: 'stairmaster',
    name: 'StairMaster',
    category: 'cardio',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: [
      'Step onto rotating stairs.',
      'Climb at a steady pace.',
      'Do not lean heavily on handrails.',
    ],
    tips: ['Great for leg endurance.', 'Keep posture upright.'],
  },
  {
    id: 'swimming',
    name: 'Swimming',
    category: 'cardio',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'Choose stroke: freestyle, breaststroke, backstroke, or butterfly.',
      'Maintain steady breathing pattern.',
      'Engage core throughout.',
    ],
    tips: ['Full body, zero impact cardio.', 'Excellent for recovery days.'],
  },
  {
    id: 'battle_ropes',
    name: 'Battle Ropes',
    category: 'cardio',
    primaryMuscles: ['shoulders', 'forearms'],
    secondaryMuscles: ['core', 'back'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'Hold ropes with both hands, knees slightly bent.',
      'Alternate raising and lowering each arm rapidly.',
      'Generate continuous waves.',
    ],
    tips: ['High intensity cardio.', 'Work in short bursts (20-30 seconds).'],
  },

  // ─── HIIT ───
  {
    id: 'burpees',
    name: 'Burpees',
    category: 'hiit',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    instructions: [
      'Drop into a squat, hands on floor.',
      'Kick feet back into push-up position.',
      'Do a push-up, then jump feet back to hands.',
      'Jump up with arms overhead.',
    ],
    tips: ['Full body conditioning.', 'Modify by stepping back instead of jumping.'],
  },
  {
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    category: 'hiit',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders', 'quads'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    instructions: [
      'Start in push-up position.',
      'Drive one knee toward chest, then switch legs rapidly.',
      'Keep hips low and core engaged.',
    ],
    tips: ['Work in intervals (e.g. 30s on, 15s off).', 'Great for cardio and core.'],
  },
  {
    id: 'box_jumps',
    name: 'Box Jumps',
    category: 'hiit',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    instructions: [
      'Stand in front of a sturdy box or platform.',
      'Squat slightly, then explode upward, jumping onto the box.',
      'Land softly with full foot on box.',
      'Step down one foot at a time.',
    ],
    tips: ['Start with a lower box height.', 'Step down, do not jump down.'],
  },
  {
    id: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    category: 'hiit',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'shoulders'],
    equipment: ['kettlebell'],
    difficulty: 'intermediate',
    instructions: [
      'Stand with feet wider than shoulders, kettlebell between legs.',
      'Hinge hips and swing kettlebell back between legs.',
      'Thrust hips forward explosively to swing kettlebell to chest height.',
      'Let kettlebell fall back between legs and repeat.',
    ],
    tips: ['Power comes from hips, not arms.', 'Keep back flat.'],
  },
  {
    id: 'sprint_intervals',
    name: 'Sprint Intervals',
    category: 'hiit',
    primaryMuscles: ['quads', 'hamstrings'],
    secondaryMuscles: ['calves', 'glutes'],
    equipment: ['none'],
    difficulty: 'advanced',
    instructions: [
      'Sprint at maximum effort for a set distance or time.',
      'Rest or walk for recovery period.',
      'Repeat for desired number of rounds.',
    ],
    tips: ['Classic HIIT exercise.', 'Example: 30s sprint, 60s walk x 8 rounds.'],
  },
  {
    id: 'thrusters',
    name: 'Dumbbell Thrusters',
    category: 'hiit',
    primaryMuscles: ['quads', 'shoulders'],
    secondaryMuscles: ['glutes', 'triceps', 'core'],
    equipment: ['dumbbell'],
    difficulty: 'intermediate',
    instructions: [
      'Hold dumbbells at shoulder height.',
      'Squat down, then as you stand, press dumbbells overhead.',
      'Lower dumbbells as you descend into next squat.',
    ],
    tips: ['Compound movement combining squat and press.', 'Very metabolically demanding.'],
  },

  // ─── Flexibility ───
  {
    id: 'static_stretching',
    name: 'Static Stretching',
    category: 'flexibility',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Hold stretch position for 15-60 seconds.',
      'Breathe deeply and relax into each stretch.',
      'Do not bounce.',
    ],
    tips: ['Best done after workout.', 'Increases range of motion over time.'],
  },
  {
    id: 'foam_rolling',
    name: 'Foam Rolling',
    category: 'flexibility',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Place foam roller under target muscle group.',
      'Roll slowly over tight spots.',
      'Pause on tender areas for 30-60 seconds.',
    ],
    tips: ['Self-myofascial release.', 'Great for recovery.'],
  },
  {
    id: 'yoga_flow',
    name: 'Yoga Flow',
    category: 'flexibility',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Move through poses like downward dog, cobra, child pose.',
      'Focus on breath and mindful movement.',
      'Hold each pose for several breaths.',
    ],
    tips: ['Improves flexibility and reduces stress.', 'Great active recovery option.'],
  },
  {
    id: 'dynamic_stretching',
    name: 'Dynamic Stretching',
    category: 'flexibility',
    primaryMuscles: ['full_body'],
    secondaryMuscles: [],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Perform controlled movements through full range of motion.',
      'Examples: leg swings, arm circles, walking lunges with rotation.',
    ],
    tips: ['Best done before workout.', 'Warms up muscles while stretching them.'],
  },

  // ─── Additional Exercises ───
  {
    id: 'farmers_walk',
    name: "Farmer's Walk",
    category: 'strength',
    primaryMuscles: ['forearms', 'traps'],
    secondaryMuscles: ['core', 'shoulders'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Hold heavy dumbbells in each hand.',
      'Walk with upright posture for set distance or time.',
      'Maintain strong grip and tall posture.',
    ],
    tips: ['Excellent grip and conditioning exercise.', 'Use weights you can hold for the full distance.'],
  },
  {
    id: 'turkish_getup',
    name: 'Turkish Get-Up',
    category: 'strength',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['shoulders', 'core'],
    equipment: ['kettlebell'],
    difficulty: 'advanced',
    instructions: [
      'Lie on back holding kettlebell overhead with one arm.',
      'Rise to standing position while keeping kettlebell overhead.',
      'Reverse the movement back to floor.',
    ],
    tips: ['Complex full-body movement.', 'Start with no weight to learn the pattern.'],
  },
  {
    id: 'clean_and_press',
    name: 'Dumbbell Clean and Press',
    category: 'strength',
    primaryMuscles: ['full_body'],
    secondaryMuscles: ['shoulders', 'traps'],
    equipment: ['dumbbell'],
    difficulty: 'advanced',
    instructions: [
      'Stand holding dumbbells at hip level.',
      'Explosively pull dumbbells to shoulder height.',
      'Press dumbbells overhead.',
      'Lower with control.',
    ],
    tips: ['Powerful compound movement.', 'Requires coordination and timing.'],
  },
  {
    id: 'sled_push',
    name: 'Sled Push',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'Load weight sled with desired weight.',
      'Push sled forward by driving through legs.',
      'Maintain low body angle and fast foot turnover.',
    ],
    tips: ['Great for leg power and conditioning.', 'Keep core engaged throughout.'],
  },
  {
    id: 'sled_pull',
    name: 'Sled Pull',
    category: 'strength',
    primaryMuscles: ['back', 'hamstrings'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'Attach rope or harness to weighted sled.',
      'Pull sled toward you while maintaining strong posture.',
    ],
    tips: ['Excellent posterior chain exercise.', 'Great for grip endurance.'],
  },
  {
    id: 'pull_over',
    name: 'Dumbbell Pullover',
    category: 'strength',
    primaryMuscles: ['chest', 'back'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: [
      'Lie across bench holding dumbbell above chest.',
      'Lower dumbbell behind head in arc motion.',
      'Pull dumbbell back over chest.',
    ],
    tips: ['Targets chest and lats.', 'Keep slight bend in elbows.'],
  },
  {
    id: 'good_mornings',
    name: 'Barbell Good Mornings',
    category: 'strength',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'back'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Place barbell on upper back.',
      'Hinge at hips, pushing butt back while keeping legs nearly straight.',
      'Lower torso until nearly parallel to floor.',
      'Drive hips forward to stand.',
    ],
    tips: ['Excellent hamstring developer.', 'Use light weight until confident with form.'],
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    category: 'strength',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    instructions: [
      'Set bar at waist height in a rack.',
      'Lie under bar and grab it.',
      'Pull chest to bar.',
      'Lower with control.',
    ],
    tips: ['Bodyweight row alternative to pull-ups.', 'Adjust difficulty by body angle.'],
  },
  {
    id: 'pistol_squat',
    name: 'Pistol Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'calves', 'core'],
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    instructions: [
      'Balance on one leg, extend other leg in front.',
      'Lower into a squat on the standing leg.',
      'Drive back up to standing.',
    ],
    tips: ['Ultimate single-leg test.', 'Progress from box pistol squats.'],
  },
  {
    id: 'muscle_up',
    name: 'Muscle-Up',
    category: 'strength',
    primaryMuscles: ['back', 'chest'],
    secondaryMuscles: ['triceps', 'biceps'],
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    instructions: [
      'Perform an explosive pull-up.',
      'Transition over the bar.',
      'Press out to full arm extension on top of the bar.',
    ],
    tips: ['Advanced gymnastic move.', 'Requires explosive pull-up strength.'],
  },
]

export const muscleGroupColors: Record<string, string> = {
  chest: 'bg-rose-500/20 text-rose-300',
  back: 'bg-emerald-500/20 text-emerald-300',
  shoulders: 'bg-amber-500/20 text-amber-300',
  biceps: 'bg-sky-500/20 text-sky-300',
  triceps: 'bg-violet-500/20 text-violet-300',
  abs: 'bg-orange-500/20 text-orange-300',
  quads: 'bg-indigo-500/20 text-indigo-300',
  hamstrings: 'bg-teal-500/20 text-teal-300',
  glutes: 'bg-pink-500/20 text-pink-300',
  calves: 'bg-cyan-500/20 text-cyan-300',
  forearms: 'bg-lime-500/20 text-lime-300',
  traps: 'bg-yellow-500/20 text-yellow-300',
  lats: 'bg-fuchsia-500/20 text-fuchsia-300',
  full_body: 'bg-primary/20 text-primary-light',
  core: 'bg-accent/20 text-accent-light',
}

export const categoryColors: Record<ExerciseCategory, string> = {
  strength: 'bg-rose-500/20 text-rose-300',
  cardio: 'bg-sky-500/20 text-sky-300',
  hiit: 'bg-orange-500/20 text-orange-300',
  flexibility: 'bg-emerald-500/20 text-emerald-300',
  plyometrics: 'bg-violet-500/20 text-violet-300',
  calisthenics: 'bg-amber-500/20 text-amber-300',
}

export const categoryLabels: Record<ExerciseCategory, string> = {
  strength: 'Strength',
  cardio: 'Cardio',
  hiit: 'HIIT',
  flexibility: 'Flexibility',
  plyometrics: 'Plyometrics',
  calisthenics: 'Calisthenics',
}

export function getExerciseById(id: string): ExerciseDefinition | undefined {
  return exerciseLibrary.find((e) => e.id === id)
}

export function searchExercises(
  query: string,
  filters?: { category?: ExerciseCategory; muscle?: MuscleGroup; equipment?: EquipmentType }
): ExerciseDefinition[] {
  const q = query.toLowerCase().trim()
  return exerciseLibrary.filter((ex) => {
    if (q && !ex.name.toLowerCase().includes(q) && !ex.primaryMuscles.some((m) => m.includes(q))) {
      return false
    }
    if (filters?.category && ex.category !== filters.category) return false
    if (filters?.muscle && !ex.primaryMuscles.includes(filters.muscle) && !ex.secondaryMuscles.includes(filters.muscle))
      return false
    if (filters?.equipment && !ex.equipment.includes(filters.equipment)) return false
    return true
  })
}

export function getExercisesByMuscle(muscle: MuscleGroup): ExerciseDefinition[] {
  return exerciseLibrary.filter(
    (ex) => ex.primaryMuscles.includes(muscle) || ex.secondaryMuscles.includes(muscle)
  )
}

export function getExercisesByCategory(category: ExerciseCategory): ExerciseDefinition[] {
  return exerciseLibrary.filter((ex) => ex.category === category)
}

export function getAllMuscleGroups(): { value: string; label: string }[] {
  const all = new Set<string>()
  exerciseLibrary.forEach((ex) => {
    ex.primaryMuscles.forEach((m) => all.add(m))
    ex.secondaryMuscles.forEach((m) => all.add(m))
  })
  return Array.from(all)
    .sort()
    .map((m) => ({ value: m, label: m.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase()) }))
}

export function getAllEquipment(): { value: string; label: string }[] {
  const all = new Set<string>()
  exerciseLibrary.forEach((ex) => ex.equipment.forEach((e) => all.add(e)))
  return Array.from(all)
    .sort()
    .map((e) => ({ value: e, label: e.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase()) }))
}
